-- Drop tables if they already exist (in correct order due to FK constraints)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE goal CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE personal_record CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE workout CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE user_account CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        NULL; -- skip errors if tables don't exist
END;
/

-- User table
CREATE TABLE user_account (
    user_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR2(50) NOT NULL UNIQUE,
    email           VARCHAR2(100),
    weight_kg       NUMBER(5,2),
    height_cm       NUMBER(5,2),
    birth_date      DATE,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Workout table
CREATE TABLE workout (
    workout_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         NUMBER NOT NULL,
    workout_date    DATE NOT NULL,
    type            VARCHAR2(50),     -- e.g., "Strength", "Cardio"
    description     VARCHAR2(4000),
    duration_min    NUMBER(5,1),
    calories_burned NUMBER(6,1),
    FOREIGN KEY (user_id) REFERENCES user_account(user_id) ON DELETE CASCADE
);

-- Personal record table
CREATE TABLE personal_record (
    pr_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         NUMBER NOT NULL,
    exercise_name   VARCHAR2(100),
    record_value    NUMBER(6,2),
    unit            VARCHAR2(20),     -- e.g., "kg", "minutes"
    record_date     DATE,
    FOREIGN KEY (user_id) REFERENCES user_account(user_id) ON DELETE CASCADE
);

-- Goal table
CREATE TABLE goal (
    goal_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         NUMBER NOT NULL,
    title           VARCHAR2(200),
    target_value    VARCHAR2(100),
    current_value   VARCHAR2(100),
    unit            VARCHAR2(20),
    deadline        DATE,
    achieved        CHAR(1) DEFAULT 'N' CHECK (achieved IN ('Y', 'N')),
    FOREIGN KEY (user_id) REFERENCES user_account(user_id) ON DELETE CASCADE
);

-- Passwords table
CREATE TABLE user_password (
                               password_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               user_id         NUMBER NOT NULL,
                               password_hash   VARCHAR2(64) NOT NULL,
                               created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                               active          CHAR(1) DEFAULT 'Y' CHECK (active IN ('Y', 'N')),
                               FOREIGN KEY (user_id) REFERENCES user_account(user_id) ON DELETE CASCADE
);




COMMIT;
